### ISSUE TITLE
Investigate EventEmitter memory leak warning

### ISSUE THREAD

**Issue by yamalight** [Exynize/exynize-runner#10]
Trace from production:

```
(node) warning: possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit.
  at Pipe.channel.onread (internal/child_process.js:444:11)
  at process.addListener (events.js:252:17)
  at process.emit (events.js:185:7)
  at Pipe.channel.onread (internal/child_process.js:444:11)
  at handleMessage (internal/child_process.js:718:10)
  at emitTwo (events.js:100:13)
  at Pipe.channel.onread (internal/child_process.js:444:11)
  at process.addListener (events.js:252:17)
```

**Comment by yamalight** [comment]
Still happens (BBC world map use case) according to kibana logs:

```
(node) warning: possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit.
  at process.<anonymous> (runner.js:90:9)
  at handleMessage (internal/child_process.js:718:10)
  at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by pke0108** [comment]
@yamalight Any news on this issue ?

**Comment by yamalight** [comment]
@PavanDevops does this still happens with latest node? I believe it was a bug in one of the older node versions

**Comment by pke0108** [comment]
@yamalight I dont see the error after restart.
